name: Starter CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup pnpm 8.x
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies 
        run: |
          pnpm install --frozen-lockfile 

      - name: Install missing dev dependencies
        run: pnpm add concurrently wait-on --save-dev
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Build Storybook
        run: pnpm build
      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && pnpm test"
